conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tavern.urls')),
]

tavern/urls.py
from django.urls import path

from . import views

app_name = 'tavern'

urlpatterns = [
    # This is the route for the home page
    path('', views.Home.as_view(), name='home'),

    # This route includes value capturing to grab the contest id as the pk variable
    # Example: localhost:8000/5/ <-- The # 5 is saved to a variable pk that we
    # can use in the view.
    path('<int:pk>/', views.Details.as_view(), name='detail'),

    # This route includes value capturing to grab the contest id as the pk variable
    path('<int:pk>/results/', views.Results.as_view(), name='results'),

    # This route includes value capturing to grab the contest id as the pk variable
    path('<int:pk>/vote/', views.Vote.as_view(), name='vote'),
]

tavern/models.py
from django.db import models


class Lunch(models.Model):
    nickname = models.CharField(max_length = 150)
    user = models.CharField(max_length = 150)
    date = models.CharField(max_length = 150)


    def __str__(self):
        return self.nickname


class Location(models.Model):
    lunch = models.ForeignKey('Lunch', on_delete=models.CASCADE)
    suggested_locations = models.CharField(max_length=100,  null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.suggested_locations

tavern/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View


from .models import Lunch
from .models import Location


class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        available_lunches = Lunch.objects.all()

        context = {
            "lunches": available_lunches
        }

        return context


class Details(TemplateView):
    template_name = "details.html"

    def get_context_data(self, **kwargs):
        available_locations = Location.objects.all()

        # The contest primary key is included on the url: locahost:8000/5/
        # We use value capturing in our urls.py to get the # 5 and save it to pk
        # The pk variable is in the dictionary self.kwargs, and we can use .get() on
        # the self.kwargs dict.
        lunch_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        lunch = Lunch.objects.get(pk=lunch_pk)

        context = {
                "details": available_locations,
                "lunch": lunch
        }

        return context


class Results(TemplateView):
    template_name = "results.html"

    def get_context_data(self, **kwargs):

        lunch_pk = self.kwargs.get('pk')
        lunch = Lunch.objects.get(pk=lunch_pk)

        context = {
                'lunch': lunch
        }

        return context


# This view will not be a template view since we won't actually show a screen.
# Once a user submits to this screen we will redirect.
class Vote(View):

    # We are going to receive a POST request with this view, so we're going to create a method called post.
    def post(self, request, **kwargs):

        lunch_pk = self.kwargs.get('pk')

        # Now that we have the primary key for the contest, use the ORM to get the
        # object from the database
        lunch = Lunch.objects.get(pk=lunch_pk)

        # The user selected a picture that they wanted to vote for in the contest.
        # They selected one of the radio buttons: <input name="photo" value="2" .../>
        # When they submitted the form, the name of the input got sent to the server with the value in the input.
        # We can use the input name get the value from the POST dictionary.
        location_voted_for_id = self.request.POST.get('location')

        # Now we want to take our contest and lookup the photo object that the user selected
        selected_location = lunch.location_set.get(pk=location_voted_for_id)

        selected_location.votes += 1
        selected_location.save()

        # Now get the URL for our results screen using the route name from urls.py
        results_url = reverse('tavern:results', args=(lunch.pk,))

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(results_url)

tavern/templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tavern</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/styles/styles.css">
</head>
<body>
<header>


</header>
   <img src="/static/tavern.png" height="500px" width="100%">

<main>
<h1 class="choose">Choose A Lunch Event You would like to take a poll on !</h1>
{% block content %}
{% endblock %}
</main>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

tavern/templates/details.html
{% extends "base.html"%}


{% block content %}

    {# Our form action needs to point to our vote route, we use the url template tag again #}
   <form action="{% url 'tavern:vote' lunch.id %}" method="post" class="row">
       {% csrf_token %}

       {% for location in lunch.location_set.all %}
            <div class="col-md-3">
                <div class="card">
                  <label for="Location{{ forloop.counter }}">
                      <h2>{{ location.suggested_locations }}</h2>
                  </label>

                       Select: <input type="radio" name="location" id="location{{ forloop.counter }}" value="{{ location.id }}" />
                </div>

            </div>

       {% endfor %}
       <input type="submit" class="btn btn-primary" value="Vote" />
    </form>


{% endblock %}

tavern/templates/home.html
{% extends "base.html"%}

{% block content %}
    {% for lunch in lunches %}
        <ul>
            <li class="list-group-item"><a href="{% url 'tavern:detail' lunch.id %}">{{ lunch.nickname }}</a></li>
        </ul>

        <p>{{ lunch.user }}</p>
        <p>{{ lunch.date }}</p>

    {% endfor %}
{% endblock %}

tavern/templates/results.html
{% extends 'base.html' %}


{% block content %}

{#    <div class="jumbotron col-md-12">#}
{#        <h1>{{ contest.title }}</h1>#}
{#    </div>#}

    <div class="col-md-8">
        <ul class="list-group">
            {% for location in lunch.location_set.all %}
                <li class="list-group-item">{{ location.suggested_locations }} -- {{ location.votes }} vote{{ location.votes|pluralize }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-4">
        <a href="{% url 'tavern:detail' lunch.id %}">Vote again?</a>
    </div>
{% endblock %}